apiVersion: apps/v1
kind: Deployment
metadata:
  name: ors-app
  labels:
    name: ors-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ors-app
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: ors-app
    spec:
      containers:
      - name: test
        image: lucasblt/ors:22
        imagePullPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: ors-app
spec:
  selector:
    name: ors-app
  ports:
    - name: port1
      protocol: TCP
      port: 1234
      targetPort: 1234
  type: LoadBalancer